# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5f1825c8a7281d754e2c1ef05cfe15938c19dec9d2a837a63a6efcfa70d5530708d23eb97551669253c8628b92ca843d82837c29e23bee2f3ac7af3baa66c33

test:
  secret_key_base: cbc9409dd96e668b1557e2b130c4e83b0a0d13e62183ca78413e45adb03bb9067da5de712f5cefedfd4372a98e4f6e464e7a93c60792e43e4e5edea22c540de9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
